server:
  port: 9091

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.162.44:8848
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true

