server:
  port: 9091

spring:
  application:
    name: order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: order_server_seata
  datasource:
    url: jdbc:mysql://pipiwanshui.mysql.rds.aliyuncs.com:3306/seata-order?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: dev_tools
    password: dev_tools
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true

eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://admin:admin-eureka@106.13.162.44:8110/eureka



