server:
  port: 9093
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev_tools
    password: dev_tools
    url: jdbc:mysql://pipiwanshui.mysql.rds.aliyuncs.com:3306/seata-account?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: account_server_seata # 事务群组（可以每个应用独立取名，也可以使用相同的名字,对应file.conf配置文件service：vgroupMapping.default）

eureka:
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name} #服务名称
    hostname: localhost
  client:
    service-url:
      defaultZone: http://admin:admin-eureka@106.13.162.44:8110/eureka
#禁止打印发送心跳任务日志
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN