server:
  port: 9090
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_account?allowMultiQueries=true
  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 106.13.162.44:8848
